### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by hhoechtl** [webdevops/Dockerfile#283]
The library `cleo` has been updated and is now incompatible.

I tried to adapt the code to the new version or pin the cleo version, but I can't get it working again as my Python skills are not very advanced.

Could somebody please assist in fixing this?

To try it, you can use this:
```
git clone https://github.com/webdevops/Dockerfile.git
cd Dockerfile
docker run -ti --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/app -w /app webdevops/dockerfile-build-env bash
root@1b50db45440f:/app# make setup
...
root@1b50db45440f:/app# make build
Traceback (most recent call last):
  File "./bin/console", line 14, in <module>
    from cleo import Application
  File "/usr/local/lib/python2.7/dist-packages/cleo/__init__.py", line 3, in <module>
    from .application import Application
  File "/usr/local/lib/python2.7/dist-packages/cleo/application.py", line 8, in <module>
    from io import UnsupportedOperation
ImportError: cannot import name UnsupportedOperation
Makefile:20: recipe for target 'build' failed
make: *** [build] Error 1
```

**Comment by Chathula** [comment]
+1 i am also facing the same issue!
