### ISSUE TITLE
liquibase:mysql fails with missing driver

### ISSUE THREAD

**Issue by ds-ronald** [webdevops/Dockerfile#314]
Trying to run any command on the container results in an error about a missing driver
Example was using 'validate'

Result:
Starting Liquibase at Thu, 01 Aug 2019 08:09:51 UTC (version 3.6.3 built at 2019-01-29 11:34:48)
Unexpected error running Liquibase: java.lang.RuntimeException: Cannot find database driver: com.mysql.cj.jdbc.Driver
liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: java.lang.RuntimeException: Cannot find database driver: com.mysql.cj.jdbc.Driver
	at liquibase.integration.commandline.CommandLineUtils.createDatabaseObject(CommandLineUtils.java:132)
	at liquibase.integration.commandline.Main.doMigration(Main.java:974)
	at liquibase.integration.commandline.Main.run(Main.java:199)
	at liquibase.integration.commandline.Main.main(Main.java:137)
Caused by: liquibase.exception.DatabaseException: java.lang.RuntimeException: Cannot find database driver: com.mysql.cj.jdbc.Driver
	at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:254)
	at liquibase.database.DatabaseFactory.openDatabase(DatabaseFactory.java:149)
	at liquibase.integration.commandline.CommandLineUtils.createDatabaseObject(CommandLineUtils.java:97)
	... 3 common frames omitted
Caused by: java.lang.RuntimeException: Cannot find database driver: com.mysql.cj.jdbc.Driver
	at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:200)
	... 5 common frames omitted

**Comment by ds-ronald** [comment]
There was an old properties file lying around in my folder that caused this
