### ISSUE TITLE
mysql.jar does not exists

### ISSUE THREAD

**Issue by luisfmcalado** [webdevops/Dockerfile#339]
Since today we are getting the following error:

```
Starting Liquibase at Mon, 17 Feb 2020 10:37:31 UTC (version 3.6.3 built at 2019-01-29 11:34:48)
Unexpected error running Liquibase: '/usr/share/java/mysql.jar' does not exist
liquibase.exception.CommandLineParsingException: '/usr/share/java/mysql.jar' does not exist
        at liquibase.integration.commandline.Main.configureClassLoader(Main.java:884)
        at liquibase.integration.commandline.Main.run(Main.java:198)
        at liquibase.integration.commandline.Main.main(Main.java:137)


For more information, please use the --logLevel flag
```

Is it related with the lastest release?

**Comment by hhoechtl** [comment]
The `openjdk:8` guys switched from mysql jdbc to mariadb jdbc. There's nothing I can do about it, you have to adapt.

**Comment by luisfmcalado** [comment]
thank you @hhoechtl.

I did a workaround.

```
liquibase:
    image: webdevops/liquibase:mysql
    depends_on:
      - mariadb
    environment:
      LIQUIBASE_CLASSPATH: "/usr/share/java/mariadb-java-client.jar"
      LIQUIBASE_DRIVER: "org.mariadb.jdbc.Driver"
      LIQUIBASE_URL: jdbc:mariadb://mariadb/test
      LIQUIBASE_USERNAME: root
      LIQUIBASE_PASSWORD: "root"
      LIQUIBASE_CHANGELOG: /changelog.sql
    volumes:
      - ./docker/liquibase/changelog.sql:/changelog.sql
```

The defaults aren't working. It's best to update the default to work with MariaDB driver.
