### ISSUE TITLE
Unable to run webdevops/php-apache-dev:7.4 on macbook air m2

### ISSUE THREAD

**Issue by xinle1030** [webdevops/Dockerfile#479]
Hi, when I tried to run webdevops/php-apache-dev:7.4 for moodle on macbook air m2 with ```docker-compose up```, this the error I got

2023-03-18 20:08:48 runtime: failed to create new OS thread (have 2 already; errno=22)
2023-03-18 20:08:48 fatal error: newosproc
2023-03-18 20:08:48 
2023-03-18 20:08:48 runtime stack:
2023-03-18 20:08:48 runtime.throw(0x4cb21f, 0x9)
2023-03-18 20:08:48     /usr/local/go/src/runtime/panic.go:566 +0x95
2023-03-18 20:08:48 runtime.newosproc(0xc42002a000, 0xc420039fc0)
2023-03-18 20:08:48     /usr/local/go/src/runtime/os_linux.go:160 +0x194
2023-03-18 20:08:48 runtime.newm(0x4d6db8, 0x0)
2023-03-18 20:08:48     /usr/local/go/src/runtime/proc.go:1572 +0x132
2023-03-18 20:08:48 runtime.main.func1()
2023-03-18 20:08:48     /usr/local/go/src/runtime/proc.go:126 +0x36
2023-03-18 20:08:48 runtime.systemstack(0x53ae00)
2023-03-18 20:08:48     /usr/local/go/src/runtime/asm_amd64.s:298 +0x79
2023-03-18 20:08:48 runtime.mstart()
2023-03-18 20:08:48     /usr/local/go/src/runtime/proc.go:1079
2023-03-18 20:08:48 
2023-03-18 20:08:48 goroutine 1 [running]:
2023-03-18 20:08:48 runtime.systemstack_switch()
2023-03-18 20:08:48     /usr/local/go/src/runtime/asm_amd64.s:252 fp=0xc420024768 sp=0xc420024760
2023-03-18 20:08:48 runtime.main()
2023-03-18 20:08:48     /usr/local/go/src/runtime/proc.go:127 +0x6c fp=0xc4200247c0 sp=0xc420024768
2023-03-18 20:08:48 runtime.goexit()
2023-03-18 20:08:48     /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4200247c8 sp=0xc4200247c0
2023-03-18 20:08:49 runtime: failed to create new OS thread (have 2 already; errno=22)

**Comment by hhoechtl** [comment]
Just fixed it be updating gosu and go-replace
